### ISSUE TITLE
Python3 and Makefile

### ISSUE THREAD

**Issue by naveedn** [AdrianPayne/fastapi-rocket-boilerplate#4]
When running through the installation guide, I needed to change `pip` to `pip3` / `python` to `python3` in order to get the setup running, as my local system is Mac Apple Silicon. Because Mac laptops have python 2.7 installed as base `python` version, I use shell aliases to map to the latest python/pip versions. Shell aliases don't appear to be expanded in Make, as `/bin/sh` is a non-interactive shell.  How do you want your users to proceed here? Open to suggestions, thanks.

**Comment by AdrianPayne** [comment]
I have included in the Readme how to proceed with the virtual environment creation. Using python3.11 -m venv venv will set the variable python to python3.11, so it is not needed to modify the makefile.

Thanks both for the issue and for the proposal!
